# Generated by Django 5.2.5 on 2025-08-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="user",
        ),
    ]
