# Generated by Django 5.2.5 on 2025-08-19 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_remove_stock_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="stock.category",
            ),
        ),
    ]
