# Generated by Django 5.2.5 on 2025-08-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_alter_stock_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="location",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
