# Generated by Django 5.2.5 on 2025-08-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_etat_stock_etat"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Stock",
            new_name="Article",
        ),
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.RenameField(
            model_name="image",
            old_name="stock",
            new_name="article",
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="article_images/"),
        ),
    ]
