# Generated by Django 5.2.5 on 2025-08-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rse", "0001_initial"),
        ("stock", "0006_rename_stock_article_alter_article_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="article",
            field=models.ManyToManyField(to="stock.article"),
        ),
    ]
