# Generated by Django 5.2.5 on 2025-08-31 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rse", "0002_alter_commande_article"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demandesponsoring",
            name="article",
        ),
    ]
