# Generated by Django 5.2.5 on 2025-08-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="matricule",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
