# Generated by Django 5.2.5 on 2025-08-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_myuser_matricule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
