# Generated by Django 5.2.5 on 2025-08-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_myuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
